---
title: "make-data for tartare?"
author:
- name: Christian Panse
  affiliation: Functional Genomics Center Zurich
  email: cp@fgcz.ethz.ch
- name: Tobias Kockmann
  affiliation: Functional Genomics Center Zurich
  email: tobias.Kockmann@fgcz.ethz.ch
package: tartare
output:
  BiocStyle::html_document
abstract: |
  xxx xxx xxx `r Githubpkg("rformassspectrometry/Spectra")`  [@Huber2015, @Trachsel2018]
vignette: |
  %\VignetteIndexEntry{Howto use the package?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography:
  - tartare.bib
---

# Sample description

# Data recording

## Q Exactive HF-X
## Fushion Lumos

# raw2mzML conversion



# Make Data (replaces `make-data.R`)




# Uploading to S3
```
#!/bin/bash

aws --profile AnnotationContributor s3 cp NestLink/F255744.RData s3://annotation-contributor/NestLink/F255744.RData --acl public-read

aws --profile AnnotationContributor s3 cp NestLink/WU160118.RData s3://annotation-contributor/NestLink/WU160118.RData --acl public-read

aws --profile AnnotationContributor s3 cp NestLink s3://annotation-contributor/NestLink --recursive --acl public-read

```
# Overview/Getting started using Bioconductor `r Biocpkg("ExperimentHub")`

load metadata

```{r eval=TRUE}
#library(kable)
fl <- system.file("extdata", "metadata.csv", package='tartare')
(metadata <- read.csv(fl, stringsAsFactors=FALSE))
```

query and load `r Biocpkg("NestLink")` package data from aws s3

```{r echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
library(ExperimentHub)

eh <- ExperimentHub(); 
query(eh, "tartare")

# load(query(eh, c("NestLink", "F255744.RData"))[[1]])
# dim(F255744)
# load(query(eh, c("NestLink", "WU160118.RData"))[[1]])
# dim(WU160118)
```


# Session info

Here is the compiled output of `sessionInfo()`:

```{r sessionInfo, echo=FALSE}
sessionInfo()
```

# References
